name: core
description: Core package for Tengu
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.1
  get_it: ^7.6.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  logger: ^2.0.2+1
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  geolocator: ^11.0.0
  device_info_plus: ^9.1.2
  google_fonts: ^6.1.0
  go_router: ^13.2.0
  internet_connection_checker: ^1.0.0+1
  equatable: ^2.0.5
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  supabase_flutter: ^2.3.4
  shelf: ^1.4.1
  shelf_router: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.11
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
